### ISSUE TITLE
Problem with like object generated with fermi_beta

### ISSUE THREAD

**Issue by landriu** [fermi-lat/pyLikelihood#18]
After installation of fermi_beta in Saclay today,  
 the following error message has been met :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 280, in T
s
    saved_state.restore()
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/LikelihoodState.py", line 59, in
 restore
    par.setDataMembers(likePar)
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/LikelihoodState.py", line 41, in
 setDataMembers
    par.setDataValues(self.par)
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/SrcModel.py", line 310, in __get
attr__
    return getattr(self.parameter, attrname)
AttributeError: 'Parameter' object has no attribute 'setDataValues'
>>>

after having launched the following python lines :

from UnbinnedAnalysis import unbinnedAnalysis
like = unbinnedAnalysis( evfile="MergedEVENTS_1_E2.fits", scfile="ft2_july09_pass8.fits", expmap="expMap_1_E2.fits", expcube="L
iveTimeCube_1.fits", irfs="CALDB", optimizer="Minuit", srcmdl="srcModel_1_E2.xml-initial")
like.fit()
like.sourceNames()
srcname = 'LAT0004'
TS_value = like.Ts( srcname)
.../...

 Here comes the whole log of the test :

[landriu@sappcfermi] ~/dev/testFermi_beta/testG5 > python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
*** Using startup saving python history in ~/.pyhistory ***
>>> from UnbinnedAnalysis import unbinnedAnalysis
srcname = 'LAT0004'
TS_value = like.Ts( srcname)
>>>
>>> like = unbinnedAnalysis( evfile="MergedEVENTS_1_E2.fits", scfile="ft2_july09_pass8.fits", expmap="expMap_1_E2.fits", expcub
e="LiveTimeCube_1.fits", irfs="CALDB", optimizer="Minuit", srcmdl="srcModel_1_E2.xml-initial")
>>>
>>> like.fit()
 **********
 **    1 **SET PRINT    2.000
 **********
 **********
 **    2 **SET NOWARN
 **********
 PARAMETER DEFINITIONS:
    NO.   NAME         VALUE      STEP SIZE      LIMITS
     1 'Prefactor '    8.7254       1.0000         .10000E-04   .10000E+06
     2 'Index     '    1.9375       1.0000          .0000       5.0000
     3 'norm      '    2.4551       1.0000          .0000       .10000E+06
     4 'alpha     '    1.2867       1.0000          .0000       5.0000
     5 'beta      '    4.3123       1.0000        -10.000       10.000
     6 'Integral  '    7.6199       1.0000          .0000       100.00
     7 'Index     '   -2.0834       1.0000        -5.0000        .0000
     8 'Prefactor '    5.2408       1.0000          .0000       100.00
     9 'Normalizat'    1.3495       1.0000          .0000       100.00
    10 'Value     '    .98731       1.0000          .0000       10.000
 **********
 **    3 **SET ERR    .5000
 **********
 **********
 **    4 **SET GRAD    1.000
 **********
 **********
 **    5 **MINIMIZE    1700.       2.000
 **********
 FIRST CALL TO USER FUNCTION AT NEW START POINT, WITH IFLAG=4.
 START MIGRAD MINIMIZATION.  STRATEGY 1.  CONVERGENCE WHEN EDM .LT.  .20E-02
 FCN=   12226.60     FROM MIGRAD    STATUS=INITIATE       1 CALLS        2 TOTAL
                     EDM= unknown      STRATEGY= 1      NO ERROR MATRIX
  EXT PARAMETER               CURRENT GUESS       STEP         FIRST
  NO.   NAME        VALUE          ERROR          SIZE      DERIVATIVE
   1  Prefactor     8.7254        1.0000        .10724E-02   -417.29
   2  Index         1.9375        1.0000        .42552       -6.6310
   3  norm          2.4551        1.0000        .20634E-02   -1526.3
   4  alpha         1.2867        1.0000        .50088        13.580
   5  beta          4.3123        1.0000        .11122        13.845
   6  Integral      7.6199        1.0000        .37769E-01   -13.031
   7  Index        -2.0834        1.0000        .41898       -8.6898
   8  Prefactor     5.2408        1.0000        .45074E-01    3.5005
   9  Normalizat    1.3495        1.0000        .94734E-01   -6.0065
  10  Value         .98731        1.0000        .46108       -19.721
                               ERR DEF=  .500
 NO ERROR MATRIX
 FCN=   12226.44     FROM MIGRAD    STATUS=PROGRESS       5 CALLS        6 TOTAL
                     EDM=   .12E+03    STRATEGY= 1      NO ERROR MATRIX
  EXT PARAMETER               CURRENT GUESS       STEP         FIRST
  NO.   NAME        VALUE          ERROR          SIZE      DERIVATIVE
   1  Prefactor     8.7263        1.0000        .93563E-06   -389.57
   2  Index         1.9432        1.0000        .23410E-02   -5.9485
   3  norm          2.4614        1.0000        .12671E-04   -1207.9
   4  alpha         1.2722        1.0000       -.66428E-02    11.396
   5  beta          4.3093        1.0000       -.33392E-03    11.918
   6  Integral      7.6209        1.0000        .36242E-04   -12.406
   7  Index        -2.0761        1.0000        .29742E-02   -8.3730
   8  Prefactor     5.2405        1.0000       -.13867E-04    6.5141
   9  Normalizat    1.3507        1.0000        .10510E-03    24.649
  10  Value         1.0118        1.0000        .81745E-02    16.606
                               ERR DEF=  .500
 FCN=   12223.63     FROM MIGRAD    STATUS=PROGRESS      37 CALLS       38 TOTAL
                     EDM=   .52E-01  STRATEGY=1  ERROR MATRIX UNCERTAINTY= 16.1%
  EXT PARAMETER                APPROXIMATE        STEP         FIRST
  NO.   NAME        VALUE          ERROR          SIZE      DERIVATIVE
   1  Prefactor     12.521        2.5746        .11485E-02   -21.375
   2  Index         2.2974        .28970        .91374E-02    .91654
   3  norm          2.4814        .28552        .18810E-03    137.26
   4  alpha         1.2883        .15673        .35397E-03    2.2113
   5  beta          3.6753        .93509        .33881E-01   -.69366
   6  Integral      10.359        1.9201        .28182E-01    .87809
   7  Index        -2.0295        .24941       -.23422E-01   -.22466E-01
   8  Prefactor     5.2146        .73552       -.25941E-03    4.9131
   9  Normalizat    1.2572        .21653        .39816E-03    5.0262
  10  Value         .99327        .66264E-01   -.37159E-02    2.6156
                               ERR DEF=  .500
 MIGRAD MINIMIZATION HAS CONVERGED.
 MIGRAD WILL VERIFY CONVERGENCE AND ERROR MATRIX.
   START COVARIANCE MATRIX CALCULATION.
 EIGENVALUES OF SECOND-DERIVATIVE MATRIX:
         -.5482E+00   .2133E+00   .3915E+00   .4382E+00   .6298E+00   .9502E+00
          .1528E+01   .1733E+01   .1905E+01   .2760E+01
 FCN=   12223.58     FROM MIGRAD    STATUS=CONVERGED    174 CALLS      175 TOTAL
                     EDM=   .32E-03    STRATEGY= 1      ERR MATRIX NOT POS-DEF
  EXT PARAMETER                APPROXIMATE        STEP         FIRST
  NO.   NAME        VALUE          ERROR          SIZE      DERIVATIVE
   1  Prefactor     13.016        43.200        .10724E-02   -.44926
   2  Index         2.2740        3.5526        .22364       -.31861E-01
   3  norm          2.4675        .20161        .11361E-02   -2.2852
   4  alpha         1.2553        .10325        .11537        .28880E-01
   5  beta          3.8438        .61984        .11122        .26097E-01
   6  Integral      10.127        2.3798        .37769E-01   -.37731E-03
   7  Index        -2.0195        .21216        .21951       -.83291E-02
   8  Prefactor     5.0904        .63975        .45074E-01   -.13973E-01
   9  Normalizat    1.2553        .15394        .31287E-01   -.76722E-01
  10  Value         .99480        .40267E-01    .46108E-01   -.15943
                               ERR DEF=  .500
 EXTERNAL ERROR MATRIX.    NDIM= 100    NPAR= 10    ERR DEF=  .500
   .187E+04 -.119E+03  .121E+01  .236E+01 -.104E+02  .124E+02 -.123E+01  .990E+01  .364E+01 -.474E-01
  -.119E+03  .765E+01 -.786E-01 -.152E+00  .672E+00 -.797E+00  .790E-01 -.636E+00 -.235E+00  .242E-02
   .121E+01 -.786E-01  .406E-01  .390E-02  .264E-01  .421E-02 -.536E-03  .734E-02  .178E-02 -.392E-03
   .236E+01 -.152E+00  .390E-02  .107E-01 -.261E-01  .117E-01 -.123E-02  .129E-01  .425E-02 -.152E-03
  -.104E+02  .672E+00  .264E-01 -.261E-01  .385E+00 -.544E-01  .560E-02 -.564E-01 -.192E-01  .462E-03
   .124E+02 -.797E+00  .421E-02  .117E-01 -.544E-01  .568E+01 -.240E+00  .806E-01 -.209E-01  .100E-02
  -.123E+01  .790E-01 -.536E-03 -.123E-02  .560E-02 -.240E+00  .451E-01 -.743E-02  .549E-03 -.100E-03
   .990E+01 -.636E+00  .734E-02  .129E-01 -.564E-01  .806E-01 -.743E-02  .409E+00  .170E-01 -.227E-02
   .364E+01 -.235E+00  .178E-02  .425E-02 -.192E-01 -.209E-01  .549E-03  .170E-01  .237E-01 -.216E-02
  -.474E-01  .242E-02 -.392E-03 -.152E-03  .462E-03  .100E-02 -.100E-03 -.227E-02 -.216E-02  .162E-02
 ERR MATRIX NOT POS-DEF
 PARAMETER  CORRELATION COEFFICIENTS
       NO.  GLOBAL     1     2     3     4     5     6     7     8     9    10
        1   .99820  1.000 -.998  .139  .529 -.389  .121 -.134  .358  .548 -.027
        2   .99823  -.998 1.000 -.141 -.533  .392 -.121  .134 -.360 -.551  .022
        3   .39342   .139 -.141 1.000  .187  .211  .009 -.013  .057  .057 -.048
        4   .60634   .529 -.533  .187 1.000 -.408  .048 -.056  .195  .267 -.037
        5   .54968  -.389  .392  .211 -.408 1.000 -.037  .042 -.142 -.201  .018
        6   .49011   .121 -.121  .009  .048 -.037 1.000 -.475  .053 -.057  .010
        7   .48313  -.134  .134 -.013 -.056  .042 -.475 1.000 -.055  .017 -.012
        8   .37604   .358 -.360  .057  .195 -.142  .053 -.055 1.000  .173 -.088
        9   .66723   .548 -.551  .057  .267 -.201 -.057  .017  .173 1.000 -.349
       10   .44124  -.027  .022 -.048 -.037  .018  .010 -.012 -.088 -.349 1.000
 ERR MATRIX NOT POS-DEF
Final values:
  Prefactor  = 13.0163
  Index      = 2.27399
  norm       = 2.46755
  alpha      = 1.25532
  beta       = 3.84384
  Integral   = 10.1273
  Index      = -2.01951
  Prefactor  = 5.09045
  Normalizat = 1.25528
  Value      = 0.994797
 **********
 **    6 **HESSE
 **********
   START COVARIANCE MATRIX CALCULATION.
 EIGENVALUES OF SECOND-DERIVATIVE MATRIX:
          .1988E+00   .2554E+00   .4357E+00   .4729E+00   .5510E+00   .9461E+00
          .1228E+01   .1577E+01   .2076E+01   .2260E+01
 COVARIANCE MATRIX CALCULATED SUCCESSFULLY
 FCN=   12223.58     FROM HESSE     STATUS=OK            94 CALLS      269 TOTAL
                     EDM=   .17E-04    STRATEGY= 1      ERROR MATRIX ACCURATE
  EXT PARAMETER                                INTERNAL      INTERNAL
  NO.   NAME        VALUE          ERROR       STEP SIZE       VALUE
   1  Prefactor     13.016        3.8494        .30571E-04   -1.5480
   2  Index         2.2740        .27778        .88694E-02   -.90527E-01
   3  norm          2.4675        .28571        .50175E-05   -1.5609
   4  alpha         1.2553        .16577        .50941E-03   -.52114
   5  beta          3.8438        1.1378        .75478E-03    .39454
   6  Integral      10.127        3.3184        .92552E-03   -.92306
   7  Index        -2.0195        .27606        .10194E-01    .19340
   8  Prefactor     5.0904        .75163        .36270E-03   -1.1156
   9  Normalizat    1.2553        .20830        .13849E-03   -1.3462
  10  Value         .99480        .64912E-01    .16235E-03   -.92903
                               ERR DEF=  .500
 EXTERNAL ERROR MATRIX.    NDIM= 100    NPAR= 10    ERR DEF=  .500
   .148E+02 -.534E+00 -.224E-01 -.216E-01  .925E-01 -.196E-01  .232E-02  .264E-01  .238E-01 -.240E-01
  -.534E+00  .775E-01 -.108E-02 -.761E-02  .452E-01  .797E-02 -.122E-03 -.807E-02 -.354E-02 -.581E-03
  -.224E-01 -.108E-02  .816E-01  .174E-02  .124E+00 -.764E-02  .383E-03  .383E-02  .314E-03 -.130E-02
  -.216E-01 -.761E-02  .174E-02  .275E-01 -.134E+00 -.266E-01  .207E-02  .302E-02 -.182E-02 -.423E-03
   .925E-01  .452E-01  .124E+00 -.134E+00  .130E+01  .153E+00 -.122E-01 -.131E-01  .114E-01  .829E-03
  -.196E-01  .797E-02 -.764E-02 -.266E-01  .153E+00  .111E+02 -.556E+00  .241E-01 -.193E+00  .296E-01
   .232E-02 -.122E-03  .383E-03  .207E-02 -.122E-01 -.556E+00  .765E-01 -.103E-02  .116E-01 -.194E-02
   .264E-01 -.807E-02  .383E-02  .302E-02 -.131E-01  .241E-01 -.103E-02  .565E+00  .195E-02 -.673E-02
   .238E-01 -.354E-02  .314E-03 -.182E-02  .114E-01 -.193E+00  .116E-01  .195E-02  .434E-01 -.916E-02
  -.240E-01 -.581E-03 -.130E-02 -.423E-03  .829E-03  .296E-01 -.194E-02 -.673E-02 -.916E-02  .421E-02
 PARAMETER  CORRELATION COEFFICIENTS
       NO.  GLOBAL     1     2     3     4     5     6     7     8     9    10
        1   .54412  1.000 -.498 -.020 -.034  .021 -.002  .002  .009  .030 -.096
        2   .56906  -.498 1.000 -.014 -.165  .142  .009 -.002 -.039 -.061 -.032
        3   .58846  -.020 -.014 1.000  .037  .381 -.008  .005  .018  .005 -.070
        4   .78685  -.034 -.165  .037 1.000 -.710 -.048  .045  .024 -.053 -.039
        5   .82029   .021  .142  .381 -.710 1.000  .040 -.039 -.015  .048  .011
        6   .62862  -.002  .009 -.008 -.048  .040 1.000 -.604  .010 -.278  .137
        7   .60586   .002 -.002  .005  .045 -.039 -.604 1.000 -.005  .201 -.108
        8   .19071   .009 -.039  .018  .024 -.015  .010 -.005 1.000  .012 -.138
        9   .72920   .030 -.061  .005 -.053  .048 -.278  .201  .012 1.000 -.677
       10   .72088  -.096 -.032 -.070 -.039  .011  .137 -.108 -.138 -.677 1.000
Minuit fit quality: 3   estimated distance: 1.73053e-05
Minuit parameter uncertainties:
  1  3.84944
  2  0.278356
  3  0.285713
  4  0.165932
  5  1.14069
  6  3.32508
  7  0.27665
  8  0.751773
  9  0.208316
  10  0.0649174
12223.582451492613
>>>
>>> like.sourceNames()
('EXTIC443', 'LAT0004', 'LAT0005', 'PSRJ0534+2200', 'SunIC_v2', 'eg_v02', 'gal_v02')
>>>
>>> srcname = 'LAT0004'
>>>
>>> TS_value = like.Ts( srcname)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/AnalysisBase.py", line 280, in T
s
    saved_state.restore()
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/LikelihoodState.py", line 59, in
 restore
    par.setDataMembers(likePar)
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/LikelihoodState.py", line 41, in
 setDataMembers
    par.setDataValues(self.par)
  File "/dsm/saplxglast/glast/anaconda2/envs/fermi_beta/lib/python2.7/site-packages/fermitools/SrcModel.py", line 310, in __get
attr__
    return getattr(self.parameter, attrname)
AttributeError: 'Parameter' object has no attribute 'setDataValues'
>>>
>>>
(fermi_beta)

**Comment by donhorner** [comment]
I can reproduce this failure in the 1.3.0 beta.  It works on the released tools (1.2.23).  I got warnings in the py3 beta (1.9.4) setting the like statement, but those went away when I upgraded to the py3 dev version 1.9.6.  Regardless, it seems to work using either py3 version.  So, the problem seems to just be with the py2 beta.  @jasercion can you take a look?

**Comment by jasercion** [comment]
@landriu When you have a chance could you please install the following python2.7 build and verify whether the issue has been fixed?

`conda install -c conda-forge -c fermi -c fermi/label/dev fermitools=1.3.1`

**Comment by landriu** [comment]
Hi Jon,

   I did the installation, and this version fix the issue. 
I keep on testing .

Thanks a lot,
   cheers
